name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: List files
      run: ls -R

    - name: Debug
      run: |
        echo "Current directory:"
        pwd
        echo "Files in current directory:"
        ls -R
        echo "Content of __tests__/index.test.js:"
        cat __tests__/index.test.js

    - name: Run tests
      run: npm test

